load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_applicable_licenses = ["//ecclesia:license"])

licenses(["notice"])

bzl_library(
    name = "accessors",
    srcs = ["accessors.bzl"],
    visibility = ["//visibility:public"],
)
