# proto-file: ecclesia/lib/redfish/dellicius/query/query.proto
# proto-message: ecclesia.DelliciusQuery

query_id: "CablesCollection"
subquery {
  subquery_id: "Cables"
  redpath: "/Cables[*]"
  properties { property: "Id" name: "Id" type: STRING }
}
