# proto-file: third_party/ecclesia/lib/redfish/dellicius/query/query_result.proto
# proto-message: DelliciusQueryResult

query_id: "AssemblyCollector"
subquery_output_by_id {
  key: "Chassis"
  value {
    data_set {
      data {
        name: "SerialNumber"
        string_value: "MBBQTW194106556"
      }
      data {
        name: "PartNumber"
        string_value: "1043652-02"
      }
    }
  }
}
start_timestamp {
  seconds: 10
}
end_timestamp {
  seconds: 10
}