proto_library(
    name = "node_class_assignment_proto",
    srcs = ["node_class_assignment.proto"],
    visibility = [
        "//visibility:public",
    ],
)

cc_proto_library(
    name = "node_class_assignment_cc_proto",
    deps = [":node_class_assignment_proto"],
)
