licenses(["notice"])

cc_library(
    name = "version",
    srcs = ["version.cc"],
    hdrs = ["version.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_absl//absl/strings",
    ],
)
