licenses(["notice"])

filegroup(
    name = "sample_queries_in",
    srcs = [
        "query_in/assembly_in.textproto",
        "query_in/sensor_in.textproto",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sample_queries_out",
    srcs = [
        "query_out/assembly_out.textproto",
        "query_out/devpath_assembly_out.textproto",
        "query_out/devpath_sensor_out.textproto",
        "query_out/sensor_out.textproto",
    ],
    visibility = ["//visibility:public"],
)
