# proto-file: ecclesia/lib/redfish/redfish_override/rf_override.proto
# proto-message: OverridePolicy

override_content_map_uri: {
  key: "/expected/result/1"
  value: {
    override_field: [
      {
        action_replace: {
          object_identifier: {
            individual_object_identifier: [ { field_name: "TestString" } ]
          }
          override_value: {
            value: { string_value: "OverrideReplaceByField" }
          }
        }
      },
      {
        action_replace: {
          object_identifier: {
            individual_object_identifier: [
              { field_name: "TestArray" },
              {
                array_field: {
                  field_name: "TestNumber"
                  value: { number_value: 1234 }
                }
              },
              { field_name: "TestNumber" }
            ]
          }
          override_value: { value: { number_value: 54321 } }
        }
      },
      {
        action_replace: {
          object_identifier: {
            individual_object_identifier: [
              { field_name: "TestArray" },
              { array_idx: 0 },
              { field_name: "TestStruct" }
            ]
          }
          override_value: {
            value: { string_value: "OverrideReplaceByIndex" }
          }
        }
      }
    ]
  }
}
