# proto-file: third_party/ecclesia/lib/redfish/dellicius/engine/query_rules.proto
# proto-message: QueryRules

query_id_to_params_rule {
  key: "AssemblyCollectorWithPropertyNameNormalization"
  value {
    redpath_prefix_with_params {
      redpath: "/Systems"
      expand_configuration {
        level: 1
        type: BOTH
      }
    }
    redpath_prefix_with_params {
      redpath: "/Chassis"
      expand_configuration {
        level: 1
        type: NO_LINKS
      }
    }
    redpath_prefix_with_params {
      redpath: "/Systems[*]/Processors"
      expand_configuration {
        level: 1
        type: ONLY_LINKS
      }
    }
    redpath_prefix_with_params {
      redpath: "/Systems[*]/Memory"
      expand_configuration {
        level: 1
        type: BOTH
      }
    }
  }
}
